
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_engine?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: ${USER_NAME}
    password: ${PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    clean-disabled: false
file:
  max-file-size: 500KB
  extensions: png, jpg, jpeg
scheduling:
   # seconds of values
   delete-code-captcha: 3600
